### ISSUE TITLE
Sensor Requirement

### ISSUE THREAD

**Issue by oym1994** [csiro-robotics/LoGG3D-Net#1]
Hi, thanks for your great job!

I am gonna to test your work in our project. We have done some investigation before. In some lidar-based place recognition method, lidar with 360 degree data with at least 36 lines is recommended. So how about the adaptability to different lidar sensor of your method?

Thank your for your attention and keep waiting for kind response!

**Comment by kavisha725** [comment]
Hi, thanks for your interest!

We have evaluated our method on various Lidar sensors:
- KITTI odometry dataset: Velodyne HDL-64E 
- MulRan dataset: Ouster-64 
- ALITA dataset: Velodyne VLP-16

Our method is independent on the LiDAR sensor used. As long as the LiDAR scans/submaps generated are have sufficient range and density to capture the structural details of the environment you should be able to adapt our method to the sensor. 

Let me know if you need more details.

**Comment by oym1994** [comment]
Got it！ Thanks for your kind response
