### ISSUE TITLE
Eval on a custom dataset 

### ISSUE THREAD

**Issue by Stream11** [csiro-robotics/LoGG3D-Net#10]
i try to eval on wild-place dataset, Can you provide an example how to eval. thank you

**Comment by kavisha725** [comment]
Use the utility function provided [here](https://github.com/csiro-robotics/Wild-Places/blob/70ffff3b7bf8497fdc627660050f983df15c3871/scripts/eval/logg3d/logg3d_utils.py#L76) to generate latent_vectors for `database_features` and `query_features`. 
Then, use the evaluation instructions provided [here](https://github.com/csiro-robotics/Wild-Places/tree/main?tab=readme-ov-file#33-evaluation).

**Comment by kavisha725** [comment]
Use the utility function provided [here](https://github.com/csiro-robotics/Wild-Places/blob/70ffff3b7bf8497fdc627660050f983df15c3871/scripts/eval/logg3d/logg3d_utils.py#L76) to generate latent_vectors for `database_features` and `query_features`. 
Then, use the evaluation instructions provided [here](https://github.com/csiro-robotics/Wild-Places/tree/main?tab=readme-ov-file#33-evaluation).

**Comment by kavisha725** [comment]
I'll close this issue as it is a copy of the [same question](https://github.com/csiro-robotics/Wild-Places/issues/12) in the Wild-Places repo.
