### ISSUE TITLE
error when batch size larger than one

### ISSUE THREAD

**Issue by HaileyMai** [csiro-robotics/LoGG3D-Net#4]
Hello, I want to first of all thank you for your great work!

I found a problem when I trained the network with batch_size=2:
```
Exception has occurred: AttributeError       (note: full exception trace is shown but execution is paused at: <module>)
'list' object has no attribute 'to'
  File "/home/stud/maiy/LoGG3D-Net/training/train.py", line 100, in main
    batch_st = batch[0].to('cuda:%d' % dist.local_rank())
  File "/home/stud/maiy/LoGG3D-Net/training/train.py", line 174, in <module> (Current frame)
    main()
```
After I looked into the code, I think the problem lies in the collation function of dataloader which is incompatible with indexing in `train.py`:
https://github.com/csiro-robotics/LoGG3D-Net/blob/e35db4b645f6e02322effec975c8b87594c8ff02/utils/data_loaders/pointcloud_dataset.py#L176-L179

Could you please check it? Any feedback is appreciated and please let me know if I misunderstood anything. Thanks again for your work!

**Comment by kavisha725** [comment]
Hi!
Yes, you're correct. The training script only supports a batch size of 1 (i.e. 1 tuple per training step). You can increase the size of this tuple to fill up your GPU memory by increasing the `positives_per_query` and `negatives_per_query` parameters. This tends to help training. 

With pytorch DDP a single batch is allocated to each GPU during a training step. It's better to fill up this GPU memory by increasing the size of the tuple and/or increasing the number of points used in the local_consistency_loss, than using additional batches. 

Hope this helps.

**Comment by HaileyMai** [comment]
Thank you, it makes sense.

**Comment by HaileyMai** [comment]
Hi, I met some problem when I trained the model:

```
Traceback (most recent call last):
  File "/home/stud/maiy/LoGG3D-Net/training/train.py", line 173, in <module>
    main()
  File "/home/stud/maiy/LoGG3D-Net/training/train.py", line 97, in main
    for i, batch in enumerate(train_loader, 0):
  File "/usr/stud/maiy/anaconda3/envs/logg3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/usr/stud/maiy/anaconda3/envs/logg3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1326, in _next_data
    return self._process_data(data)
  File "/usr/stud/maiy/anaconda3/envs/logg3d/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/usr/stud/maiy/anaconda3/envs/logg3d/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/stud/maiy/LoGG3D-Net/training/../utils/data_loaders/kitti/kitti_sparse_dataset.py", line 243, in __getitem__
    sel_positive_ids = random.sample(
  File "/usr/stud/maiy/anaconda3/envs/logg3d/lib/python3.9/random.py", line 450, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/stud/maiy/anaconda3/envs/logg3d/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/stud/maiy/anaconda3/envs/logg3d/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/stud/maiy/anaconda3/envs/logg3d/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/stud/maiy/LoGG3D-Net/training/../utils/data_loaders/kitti/kitti_sparse_dataset.py", line 248, in __getitem__
    sel_positive_ids = random.choices(
  File "/usr/stud/maiy/anaconda3/envs/logg3d/lib/python3.9/random.py", line 487, in choices
    return [population[floor(random() * n)] for i in _repeat(None, k)]
  File "/usr/stud/maiy/anaconda3/envs/logg3d/lib/python3.9/random.py", line 487, in <listcomp>
    return [population[floor(random() * n)] for i in _repeat(None, k)]
IndexError: list index out of range

```

Do you have any idea what is going on?
Thank you for your help!

**Comment by kavisha725** [comment]
Hi, 
It looks like your train set has a query with zero positives. Unfortunately, my dataloader and train scripts cannot handle this case. This issue should be handled during the generation of training tuples. 
Did you follow `python utils/data_utils/kitti_tuple_mining.py` for offline mining of positive pairs? Did you use the 3m and 20m thresholds?

**Comment by HaileyMai** [comment]
Yes, I regenerate the positive pairs exactly following `python utils/data_utils/kitti_tuple_mining.py` with the default 3 and 20 threshold. The error occured again.

**Comment by kavisha725** [comment]
Thanks for double checking. I will modify the `utils/data_utils/kitti_tuple_mining.py` script in order to handle this and update you when that's done. 

In the meantime, could you please try the following:

-  In the error you encountered above, it should print information about the sequence ID and query ID (ie this [line](https://github.com/csiro-robotics/LoGG3D-Net/blob/e35db4b645f6e02322effec975c8b87594c8ff02/utils/data_loaders/kitti/kitti_sparse_dataset.py#L247)). Could you please share that to help me debug. Also, while I am working on this fix, you should be able to exclude that sequence from the training set and train your models (edit this [line](https://github.com/csiro-robotics/LoGG3D-Net/blob/e35db4b645f6e02322effec975c8b87594c8ff02/config/train_config.py#L80) to select training sequences). 
-  Let me know if you are using the original KITTI odometry dataset? I have tested this project using the refined ground truth provided in the SemanticKITTI dataset (http://semantic-kitti.org/dataset.html#download). I have not encountered this error using that ground truth data.

**Comment by HaileyMai** [comment]
Thanks for you kind answer. The printed info is:
```
03/26 23:45:05 Drive id:1, query id:452, ppq:2, num_pos:0
03/26 23:45:19 avg running loss: 3.459097743977227 LR: 0.001000
03/26 23:45:19 avg_scene_loss: 0.7406298885237355 avg_point_loss: 2.718467855453491
Traceback (most recent call last):
...
```

I checked again and found that the file `utils/data_utils/kitti_tuple_mining.py` is actually using the `poses.txt` provided by the SemanticKITTI dataset instead of `poses/00.txt` from kitti odometry dataset. So I am actually using the gt poses from the SemanticKITTI dataset but encountered an error that you did not meet.

**Comment by kavisha725** [comment]
Thanks for sharing. 
I've added a temporary fix to address this issue in the latest commit. You should be able to use this fix to train on all sequences now. 

I am planning to re-write my dataloader and training scripts to make them more simpler. During those changes I will include a more elegant solution to this issue. 

Hope this helps.

**Comment by kavisha725** [comment]
Closing this issue as it is resolved. If you run into additional problems during training please create a new issue.
