### ISSUE TITLE
Issues with training KITTI datset

### ISSUE THREAD

**Issue by DineshchandarR** [csiro-robotics/LoGG3D-Net#5]
Dear Authors,

At the outset, I would like to thank you for your great work and for making this code public.
But when I was trying to execute training for KITI dataset with the  default training parameters, I am getting the following errors:
[mpiexec@node0006] match_arg (utils/args/args.c:163): unrecognized argument allow-run-as-root
[mpiexec@node0006] HYDU_parse_array (utils/args/args.c:178): argument matching returned error
[mpiexec@node0006] parse_args (ui/mpich/utils.c:1642): error parsing input array
[mpiexec@node0006] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1694): unable to parse user arguments
[mpiexec@node0006] main (ui/mpich/mpiexec.c:148): error parsing parameter

Any feedback/ insights on the same are appreciated.

Thanks for your time and your work.

**Comment by kavisha725** [comment]
Hi, 
Can you confirm whether you have followed the 2 steps below when setting up your environment:
`conda install mpi4py`
`conda install openmpi`

If the above doesn't resolve your issue, please share your outputs for:
`conda list`
and
your train config file.

**Comment by DineshchandarR** [comment]
Dear Kavisha,

Thank you for your quick reply.
And yes, I have installed the following in my environment:
>mpi4py
>openmpi
Kindly find the attached output from my environment and train config file.

Thanks again for your time and assistance.

[train_config.txt](https://github.com/csiro-robotics/LoGG3D-Net/files/11246230/train_config.txt)
nment list.
[conda_envs.txt](https://github.com/csiro-robotics/LoGG3D-Net/files/11246194/conda_envs.txt)

**Comment by kavisha725** [comment]
Could you also share the command you use to run training? Are you training on a cluster? How many gpus do you use? Are you using slurm?

**Comment by DineshchandarR** [comment]
Iam using 1 GPU, and running it on a cluster system.
Following is the commands:
_NGPU=1
torchpack dist-run -np ${_NGPU} python training/train.py \
    --train_pipeline 'LOGG3D' \
    --dataset 'KittiPointSparseTupleDataset'

**Comment by kavisha725** [comment]
Thanks for the information. 

I'm unable to re-create this issue. Could you please run this outside the cluster and let me know if you still get the same error?
[dist.init()](https://github.com/csiro-robotics/LoGG3D-Net/blob/1c44f9e367185dd6d947e3070f591fd83d2dcaf0/training/train.py#L28) might require a different configuration on your cluster.

**Comment by DineshchandarR** [comment]
Thanks for your assistance; I am able to initiate the training on my desktop now.
Can I get more details on loss during Kitti training?
Thanks again for your assistance on the same.

**Comment by kavisha725** [comment]
The log file for training on KITTI 08 is attached. You can see how each of the losses reduce during training. 
[kitti08_log.txt](https://github.com/csiro-robotics/LoGG3D-Net/files/11438251/kitti08_log.txt)
