### ISSUE TITLE
Train on a custom dataset

### ISSUE THREAD

**Issue by 4ku** [csiro-robotics/LoGG3D-Net#6]
Can you provide an example how to train on a custom dataset?

**Comment by kavisha725** [comment]
Thanks for your interest. 
Please check the latest commit: I've added new [general dataloaders](https://github.com/csiro-robotics/LoGG3D-Net/tree/main/utils/data_loaders/general) to help with training LoGG3D on custom datasets. 
- You will need to define training tuples (in pickle format) for you custom dataset and set the pickle file location [here](https://github.com/csiro-robotics/LoGG3D-Net/blob/68c97cbd77d3b8447211ab03f0fa6d9927be9398/config/train_config.py#L108). 
- We follow the tuple generation convention of EgoNN: see [here](https://github.com/jac99/Egonn/blob/main/datasets/mulran/generate_training_tuples.py) for an example of how training pickles are generated for the MulRan dataset.

**Comment by 4ku** [comment]
Thank you very much for quick response!
