### ISSUE TITLE
about visualization of t-SNE embeddings of the local features

### ISSUE THREAD

**Issue by FengYuQ** [csiro-robotics/LoGG3D-Net#8]
how to Visualize the t-SNE embeddings of the local features？ Have any code provide？Thanks！

**Comment by kavisha725** [comment]
Please refer to the code from FCGF: 
https://github.com/chrischoy/FCGF/blob/0612340ead256adb5449da8088f506e947e44b4c/util/visualization.py#L30

Make sure to vertically stack the point clouds before calculating tsne embeddings.

**Comment by FengYuQ** [comment]
@kavisha725 Thans for your reply！I found that the number of raw point cloud or down sample point cloud is different from the number of featrue which was extracted.sSo how should I colorized each point in this situation?

**Comment by kavisha725** [comment]
See the example [compute_embedding()](https://github.com/csiro-robotics/SpectralGV/blob/942dd14b1ea33c26a7494f0cf5f1b09f0f4a2843/evaluation/LoGG3D-Net/eval_logg3d_sgv.py#L387) function on how to extract an equal number local features from a point cloud using the LoGG3D network. 

The `keypoints, key_embeddings` variables returned from this function will be equal in length.

**Comment by FengYuQ** [comment]
> See the example [compute_embedding()](https://github.com/csiro-robotics/SpectralGV/blob/942dd14b1ea33c26a7494f0cf5f1b09f0f4a2843/evaluation/LoGG3D-Net/eval_logg3d_sgv.py#L387) function on how to extract an equal number local features from a point cloud using the LoGG3D network.



![image](https://github.com/csiro-robotics/LoGG3D-Net/assets/34698988/8d18807b-756d-4147-8ba2-381e6cdf17fa)
![image](https://github.com/csiro-robotics/LoGG3D-Net/assets/34698988/67b24f94-2db0-4478-b8ac-2e82ad930929)
I see the example comute_embediding() function, but i still can't get the equal number local features from a point cloud. the first matrix on seond picture is the feature.shape and the second matrix is piont cloud shape. anything wrong in my code?

**Comment by kavisha725** [comment]
The shape of the base_pcd will be different. Local features are only calculated for the return of the make_sparse_tensor() function. Please use the comute_embediding() function as is. It handles your problem.

**Comment by FengYuQ** [comment]
It is work!Thank for your guide!
