### ISSUE TITLE
Question about the construction of the is_revisit_D-3_T-30.json file?

### ISSUE THREAD

**Issue by shenhai911** [csiro-robotics/LoGG3D-Net#9]
Dear author, 
        Thank you for your incomparable work. I want to ask you a question. How is is_revisit_D-3_T-30.json constructed?
        Thank you very much for your reply.

**Comment by kavisha725** [comment]
Hi, 
Please see the following files:
https://github.com/csiro-robotics/LoGG3D-Net/blob/main/utils/data_utils/kitti_tuple_mining.py
https://github.com/csiro-robotics/LoGG3D-Net/blob/main/utils/data_utils/mulran_tuple_mining.py
